apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.23
        ports:
          - containerPort: 9200
          - containerPort: 9300
        env:
          - name: ES_JAVA_OPTS
            value: '-Xms512m -Xmx512m'
          - name: discovery.type
            value: single-node

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
    - targetPort: 9200
      port: 9200
