CHAIN_ETHER = 'ETHER'
CHAIN_TRON = 'TRON'

CURRENCY_ETHER_ETH = 'ETHER_ETH'
CURRENCY_ETHER_USDT = 'ETHER_USDT'
CURRENCY_TRON_TRX = 'TRON_TRX'
CURRENCY_TRON_USDT = 'TRON_USDT'

ETHER_NODE_URL = 'https://ropsten.infura.io/v3/...'
ETHER_SCAN_API_KEY = '...'
ETHER_USDT_ADDRESS = '...'
ETHER_USDT_ABI_PATH = 'abi/ether_usdt_abi.json'

TRON_NETWORK = 'shasta'
TRON_USDT_ADDRESS = '...'
